version: '3.7'

services:
  akababi-db:
    image: mysql:8.0.31
    container_name: akababi-db
    restart: always
    environment:
      MYSQL_DATABASE: akababi
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql
    hostname: akababi-db
    networks:
      - akababi-network

  akababi-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: akababi-api
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./api/${CUSTOM_PATH}:/usr/src/app/private
      - ./api/${UPLOAD_PATH}:/usr/src/app/uploads
    depends_on:
      - akababi-db
    hostname: akababi-api
    networks:
      - akababi-network

networks:
  akababi-network: