name: Docker build and deploy

on:
  push:
    branches:
      - api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Docker build and push
        with:
          image: burka9/akababi-api
          tags: v1
          registry: docker.io
          directory: api
          dockerfile: api/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
